package buzzword;

/**
 * @author Jason Kang
 */
public enum BuzzWordProperties {
    WORKSPACE_TITLE_LABEL,
    CREATE_PROFILE_LABEL,
    LOGIN_LABEL,
    SELECT_MODE_LABEL,
    START_PLAYING_LABEL,
    HOME_LABEL,
    ROOT_STACKPANE_ID,
    MENU_BUTTON_UNSELECTED,
    MENU_BUTTON_SELECTED,
    MENU_BUTTON_MODE,
    MENU_BUTTON_MODEDISPLAY,
    TITLE_LABEL;
}

