package buzzword;

/**
 * @author Jason Kang
 */
public enum BuzzWordProperties {
    WORKSPACE_TITLE_LABEL,
    CREATE_PROFILE_LABEL,
    LOGIN_LABEL,
    SELECT_MODE_LABEL,
    START_PLAYING_LABEL,
    HOME_LABEL,

    // BUTTON CSS
    ROOT_BORDERPANE_ID,
    CLOSE_BUTTON_IMAGE,
    PAUSE_BUTTON_IMAGE,
    PLAY_BUTTON_IMAGE,

    // GRID BUTTON CSS
    GRID,
    GRID_OPENLEVEL,
    GRID_SELECTED,


    TITLE_LABEL,
    REMAINING_LABEL,
    MODE_LABEL,

    // GAME OPTION
    ENGLISH_DICTIONARY,
    PLACES,
    SCIENCE,
    FAMOUS_PEOPLE;

}

